
package MapEntity;
import OdysseiaGame.OdysseiaGame;
import java.math.BigInteger;
import java.util.Random;

/**
 * Created by Brian on 10/11/2014.
 */

public abstract class MapEntity {
    private String id;
    public String name;
    public String description;
    private double longitude;
    private double latitude;
    private float triggerRadiusInMeters;
    public MarkerType markerType;

    private OdysseiaGame game;
    private boolean isActive;

    // TODO: set id to one generated by Firebase (generated by whatever creates the marker)
    public MapEntity(double lat, double lon, String name, OdysseiaGame game, MarkerType markerType) {
        this.id = "tochange"
        this.longitude = lon;
        this.latitude = lat;
        this.game = game;
        this.name = name;
        this.markerType = markerType;
    }

    public void setName(String newName) {
        this.name = newName;
    }

    public String getName() {
        return this.name;
    }

    public void setCoordinates(double lat, double lon) {
        this.longitude = lon;
        this.latitude = lat;
    }

    public double getLatitude() {
        return this.latitude;
    }

    public double getLongitude() {
        return this.longitude;
    }

    public boolean isActive() {
        return this.isActive;
    }

    public void turnOff() {
        this.isActive = false;
    }

    public void setTriggerRadius(float meters) {
        this.triggerRadiusInMeters = meters;
    }

    public float getTriggerRadius() {
        return this.triggerRadiusInMeters;
    }

    public enum MarkerType {
        QUEST, ITEM, NPC, MONSTER;

        @Override public String toString() {
            // all lowercase, as is stored
            return super.toString().toLowerCase();
        }
    }
}
